### ISSUE TITLE
TeX2img の PDF からの画像化がウイルスバスタークラウドにブロックされる

### ISSUE THREAD

**Issue by aminophen** [abenori/TeX2img#1]
# [Mac 版の Issue](https://github.com/doraTeX/TeX2img/issues/64#issuecomment-165998283) の脱線から飛んできました。

TeX2img の PDF からの画像変換処理中に3回に1回くらい[ウイルスバスターにブロックされる](https://github.com/doraTeX/TeX2img/issues/56#issuecomment-154311259)ので、不思議に思って調べています。これはソース埋め込み有無や出力形式によらず、特にアウトライン化を経る場合に落ちやすくなっています。

> 「ウイルスバスタークラウド10」をインストールしたのですが、そのあとから「ソース埋め込み」のときに時々ブロックされて、TeX2img のプロセスが落とされるという現象に見舞われました。

クラウド10になったときから、ファイルの変更監視が厳しくなったのだと思っています。現在のベータ版の EMF 出力を例に調べると、最初の pdfTeX 実行が終わった直後に高確率で落ちます。

> 「安全ではない可能性があるプログラムがファイルを変更、または暗号化しました。安全のためプログラムを停止します。このプログラムが変更した次のファイルを復元できません。」
> - プログラム：tex2img.exe
> - 変更されたファイル：PDF ファイルの名前が3つ並ぶ

3回に2回くらいは正常に処理終了するのが不思議なのですが、その場合の一時ファイルを照らし合わせてみると、どうやら TeX2img の処理中に一時ファイルをどんどん上書きするのが原因だと思います。

**Comment by aminophen** [comment]
以下は「入力：テキスト保持 PDF、出力：アウトライン化 EMF」の場合（gs9.10 使用）で調べています。
EMF ファイルが正常に生成した場合、最終的に残る一時ファイルは

- nsvzaeko.pdf：入力ファイルと同じタイムスタンプ（dvipdfmx で作成）
- l3mhsekm.tex, l3mhsekm.log
- z00lzv3j.pdf：テキスト保持 PDF（アプリケーション：TeX、PDF変換：Ghostscript 9.10）
- 5t0tqaxy-1.eps：アウトライン化 EPS
- 5t0tqaxy.pdf：クロップ済みアウトライン化 PDF；破線変形済み（アプリケーション：Ghostscript (epswrite)、PDF変換：Ghostscript 9.10）
- log1aehc.pdf：クロップ済みアウトライン化 PDF（アプリケーション：Ghostscript (epswrite)、PDF変換：Ghostscript 9.10）

です。これを内部処理と照らし合わせると、5t0tqaxy.pdf がどんどん上書きされて次へ進んでいることに気づきました。たぶんそこでブロックされているようです。

**Comment by abenori** [comment]
後で見てみますが，確かに上書き処理をしたりしているところがいくつかあった気がします．極力新しいファイルにするようにやってみます．（しかし「ファイルを何度も上書きしているからウイルス」とかどんだけ有用なんだろうか……）

**Comment by aminophen** [comment]
「pdfTeX でコンパイルしてでてきたファイルをリネーム（移動）して結果的にファイルを上書き」のような処理がどうも駄目なようで、ほかはすんなり通るようにも見えます。子プロセスが上書きした場合の「gswin32c.exe をブロックした」という表示は手元では出ず、常にブロックされるのは tex2img.exe みたいです。

**Comment by abenori** [comment]
TeX2imgが呼び出したプログラムが上書きするということは（たぶん）ないようにしていると思います．たとえばpdftexでA.pdfをサイズ調整する場合は，A.pdfをtmp.pdfにリネームして，pdfprocをかけてできたファイルをA.pdfにリネームしています．gsver<9.15のemf変換では，そういうことを三回しているみたいですので，それが原因なんですかねぇ．しかしこれをやめるとなると結構見通しの悪い感じになりそうなので，少し考えます．

**Comment by abenori** [comment]
https://onedrive.live.com/redir?resid=4FABCB4EC4FA1E70!16825&authkey=!ANYoMX5Yq7PLXU4&ithint=folder%2cexe

削除/移動を減らしてみました．これで改善するでしょうか？

**Comment by aminophen** [comment]
20回くらい試しましたが、いまのところブロックされていません。たぶん改善していると思います。

- テキスト保持とアウトライン化が逆転しています…（内部のフラグが逆でややこしいんですね）
- gs9.14 以下のアウトライン化（EPS 経由）EMF 出力で、右上に大きな余白ができます。PDF 出力などでは起きていないので、理由がまったくわかりません…

**Comment by abenori** [comment]
ちょっと使ってみてください．という感じでしょうかね．

> あ、設定画面のタブが減っているので、その変更前のものに戻ったっぽい？

なんか変ですね．もう一度あげてみました．
