### ISSUE TITLE
English language installation difficulties

### ISSUE THREAD

**Issue by gapster** [abenori/TeX2img#10]
I'm installing TeX2img 2.10 on Windows 10 / TeX Live.  I followed the instructions in [this Stack Exchange answer (in the comments)](https://tex.stackexchange.com/a/323795/42887) but I get this error:   

> C:\Users\gpajer\AppData\Local\Temp>"C:\texlive\2017\bin\win32\pdflatex.exe" -interaction=nonstopmode upjia0e3.tex
> This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/W32TeX) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> (./upjia0e3.tex
> LaTeX2e <2017-04-15>
> Babel <3.18> and hyphenation patterns for 46 language(s) loaded.

[...]

> (c:/texlive/2017/texmf-dist/tex/latex/graphics-def/pdftex.def))
> No file upjia0e3.aux.
> (c:/texlive/2017/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
> [Loading MPS to PDF converter (version 2006.09.02).]
> )
> 
> ! LaTeX Error: Can be used only in preamble.

Here is my preamble:

> %latex: pdflatex
> \documentclass[fleqn]{article}
> \usepackage{amsmath,amssymb}
> \usepackage{xcolor}
> \pagestyle{empty}
> 
> 

I hope that's enough information for you.  If not, let me know.
Gary

**Comment by doraTeX** [comment]
Your preamble and the running compiler are consistent and look appropriate. I suppose you are using in the document body some commands which are allowed only in preamble such as `\usepackage`. Please try replacing the document body with simpler contents such as `$x$` in order to isolate the issue.

**Comment by abenori** [comment]
You must not write `\begin{document}` and `\end{document}` in the main body of input, so you should write only `Hello World`. TeX2img automatically inserts `\begin{document}` and `\end{document}`.

**Comment by gapster** [comment]
That does it.  Thank you.
