### ISSUE TITLE
Issue when generating EMF to charge it in Power point (using windows 10) (does not generate EMF file when I create a vector entry from Iguanatex)

### ISSUE THREAD

**Issue by martigomaria** [abenori/TeX2img#13]
It starts to convert from latex to pdf but in the step when it has to create a EMF file to charge it to power point it stops. I guess the problem cames from the pdfiumdraw.exe step. 

In Tex2img appears the following output:
>"F:\Programas\TeX2img\pdfiumdraw.exe" --extent=50 --emf --transparent --pages=1 --output="c4nvcxw0-%d.emf" "c4nvcxw0.pdf"
output: F:\Maria\Prueba Iguanatex\c4nvcxw0-1.emf 

And after 60 seconds waiting for a response, it appers the following error:
![screenshot](https://user-images.githubusercontent.com/66833493/84507164-b2b31300-acc0-11ea-8ae4-f9582aeeccc6.PNG)

- I have tested to create a EMF file in TeX2img and it works perfectly. 
-Iguanatex generates a temporary file called "IguanaTex_tmp.emf" with the entry that i defined in IguanaTex. However, it is unable to charge it to power point. 

Any guess why?

**Comment by abenori** [comment]
Can you give me an example of a LaTeX source code which causes a problem?

**Comment by martigomaria** [comment]
Sure. With the following code, I am not having any problem if a create a bitmap iguanaTex output. However, I encourage the problem I described below if I try to generate a vector output. 

\documentclass{article}
\usepackage{amsmath}
\pagestyle{empty}
\begin{document}
$i_{12}$
\end{document}

**Comment by abenori** [comment]
Thank you. I tried with your source but it in fact did not fail. I'll try to figure out what is happening, but maybe not soon...
Did you ask it to the developer of IguanaTeX? Because you succeed to generated a EMF file with TeX2img, it is possible that there is some reason with IguanaTeX. I think it worth to do it.

**Comment by Jonathan-LeRoux** [comment]
(Developer of IguanaTex here ;) )
I'm happy to look into this if that's still an issue. First thing to try is to run IguanaTeX with the Debug box checked, then open a command line, cd to the IguanaTex Temp folder, paste the TeX2img command that was copied to the clipboard, and run it.
There must be some issue with paths. 
If I had to take a guess, I would say that you put tex2img.exe instead of tex2imgc.exe as the TeX2img path in the IguanaTex settings.

**Comment by amirweiss15** [comment]
Hi, I also have exactly the same bug, and I made sure that I have 'tex2imgc.exe' rather than 'tex2img.exe' in my IguanaTex settings, so that's not the issue like Jonathan had hypothesized.
Can anyone help with this? Tried several things, but I'm bit a stuck here

**Comment by Jonathan-LeRoux** [comment]
Did you try the debugging steps I mentioned in IguanaTeX?

**Comment by amirweiss15** [comment]
Yes, of course. I went over [this page](https://www.jonathanleroux.org/software/iguanatex/faq.html). However, there is nothing about the error message that appears in the screenshot above ("Tex2img did not return in 60 seconds..."). 
It should be mentioned that I see it after a few seconds, not 60. Moreover, I tried changing the number of second in the respective field, and it gives the same message, with the number of seconds modified, but the message appears after (approximately or the same, haven't measured exactly) period of time.

**Comment by Jonathan-LeRoux** [comment]
Just to confirm, what happens if you run the compilation in IguanaTeX with the Debug box checked, then open a command line, cd to the IguanaTex Temp folder, paste the TeX2img command that was copied to the clipboard, and run it?
As a workaround, I would suggest using SVG instead of EMF for vector graphics. It's available in the latest version of IguanaTex.

**Comment by amirweiss15** [comment]
Well, it's a very long output, but the end of it is:
![image](https://github.com/abenori/TeX2img/assets/46974964/e5874647-a9b9-4f78-80e1-43bd4c52ef70)
How do I try the workaround? Where do I change from EMF to SVG?
And thanks for helping with this! Much appreciated!

**Comment by abenori** [comment]
Is it possible to give the command line and the source file which TeX2img tried to compile? It will be helpful.

**Comment by amirweiss15** [comment]
I updated to the latest version of IguanaTex v1.60.2, and when I generate with Latex Engine "latex (DVI)" and "Vector", I get this error message:
![image](https://github.com/abenori/TeX2img/assets/46974964/8c635ff4-6a9b-4670-b57b-51f92086a8f9)

**Comment by Jonathan-LeRoux** [comment]
Maybe your version of Office doesn't support SVG. I believe it's only on Office 2019 and 365.
You can try switching the vector setting back to EMF, but you'll likely be back to the tex2img issue.

**Comment by amirweiss15** [comment]
Yes, that's where I am now

**Comment by abenori** [comment]
I compiled the following source file with the command line you showed. 

```
\documentclass{article}
\begin{document}
$x = y$
\end{document}
```

I didn't get any error. Could you give me more information. The source file should be helpful. It would be also good if you give me a full log file.

**Comment by Jonathan-LeRoux** [comment]
One thing to confirm is, can you compile the same source in the Tex2img GUI.

**Comment by amirweiss15** [comment]
I tried to generate the source code:
\documentclass{article}
\begin{document}
$x = y$
\end{document}
directly in the Tex2ing GUI. I got this error message:
![image](https://github.com/abenori/TeX2img/assets/46974964/64a1e64b-408d-4046-8061-44a45cda213e)
and here's the output:
**********************************************************************************************
C:\Users\amirw\AppData\Local\Temp>"C:\Users\amirw\AppData\Local\Programs\MiKTeX\miktex\bin\x64\latex.exe" -interaction=nonstopmode wjxgurqp.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.4) (preloaded format=latex.fmt)
 restricted \write18 enabled.
entering extended mode
(wjxgurqp.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-03-30>
(C:\Users\amirw\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(C:\Users\amirw\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\amirw\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-dvi
ps.def)
No file wjxgurqp.aux.
[1] (wjxgurqp.aux) )
Output written on wjxgurqp.dvi (1 page, 300 bytes).
Transcript written on wjxgurqp.log.

C:\Users\amirw\AppData\Local\Temp>"C:\Users\amirw\AppData\Local\Programs\MiKTeX\miktex\bin\x64\latex.exe" -interaction=nonstopmode wjxgurqp.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.4) (preloaded format=latex.fmt)
 restricted \write18 enabled.
entering extended mode
(wjxgurqp.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-03-30>
(C:\Users\amirw\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(C:\Users\amirw\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\amirw\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-dvi
ps.def) (wjxgurqp.aux) [1] (wjxgurqp.aux) )
Output written on wjxgurqp.dvi (1 page, 300 bytes).
Transcript written on wjxgurqp.log.

C:\Users\amirw\AppData\Local\Temp>"C:\Users\amirw\AppData\Local\Programs\MiKTeX\miktex\bin\x64\dvipdfmx.exe" wjxgurqp.dvi
wjxgurqp.dvi -> wjxgurqp.pdf
[1]
2997 bytes written

C:\Users\amirw\AppData\Local\Temp>"C:\Program Files\gs\gs10.01.1\bin\gswin64c.exe" -q -dBATCH -dNOPAUSE -sDEVICE=bbox -dFirstPage=1 -dLastPage=1 "wjxgurqp.pdf"
%%BoundingBox: 149 139 308 712
%%HiResBoundingBox: 149.003995 139.247996 307.313991 711.539978


C:\Users\amirw\AppData\Local\Temp>"C:\Program Files\gs\gs10.01.1\bin\gswin64c.exe" -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dAutoRotatePages=/None -dCompatibilityLevel=1.5 -r20016 -dNoOutputFonts -dFirstPage=1 -dLastPage=1 -sOutputFile="ekidilfq.pdf" -c ".setpdfwrite" -f "wjxgurqp.pdf"
GPL Ghostscript 10.01.1 (2023-03-27)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Error: /undefined in .setpdfwrite
Operand stack:
GPL Ghostscript 10.01.1: Unrecoverable error, exit code 1

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:777/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
**********************************************************************************************

**Comment by abenori** [comment]
Which version of TeX2img are you using? It seems to be before 2.1.0.

**Comment by amirweiss15** [comment]
I have 2.1.0.0

**Comment by abenori** [comment]
The latest version is 2.2.1, so please download it from https://www.ms.u-tokyo.ac.jp/~abenori/soft/index.html#TEX2IMG and update it.

**Comment by amirweiss15** [comment]
I just downloaded it, updated the settings, and tried to generate. It gave me the same error

**Comment by abenori** [comment]
Did you really get the same error? In the previous post the error comes from `.setpdfwrite` command, but in the latest version the usage of this command is removed, so it is very strange for me. Could you please check the full log file and the version again?

**Comment by amirweiss15** [comment]
I have no errors when I generate an eps file via Tex2img GUI.

**Comment by abenori** [comment]
Maybe you should switch the vector setting back to EMF?

**Comment by amirweiss15** [comment]
It works with no errors with EMF.
Thanks a lot to both of you for your help!

**Comment by koppor** [comment]
I might be that users installed the **version 2.1.0.0** via the "Download" link of Inguana TeX (refs https://github.com/Jonathan-LeRoux/IguanaTex/issues/74).

Check `--version` output. Here, it was `TeX2img Version 2.1.0.0`, which has this issue. Using **latest versoin** 2.2.1.0 solved the issue

@abenori You can close the issue IMHO.

**Comment by Jonathan-LeRoux** [comment]
I'll update the link in the next version, thanks!

Regarding @amirweiss15's issue when using SVG: Office 2021 normally supports SVG, except for volume licensed versions (at version 1808 as of August 2023), so I'm assuming that's the case here.
