### ISSUE TITLE
出力先ファイルのプルダウンボックスで選んだ拡張子を［参照］で反映する

### ISSUE THREAD

**Issue by kuroky49** [abenori/TeX2img#15]
/** Feature Request */

出力先ファイルのプルダウンボックスで拡張子を選ぶと，第一画面のファイル名は切り替わりますが，［参照］を押したときには（初期設定では）EPS ファイルで探しに行ってしまうようです．

プルダウンボックスで選んだ拡張子で検索しに行くようになっているほうが，ユーザが自然と感じる振舞いになると思われます．

**Comment by abenori** [comment]
ffa6dfd で対応したつもり．

**Comment by kuroky49** [comment]
Version 2.1.3.0 で既存のファイルを全部上書きして試してみたつもりなのですが，.eps で一覧が出ます．

**Comment by kuroky49** [comment]
どこかキャッシュを消して試す必要があるでしょうか？

**Comment by abenori** [comment]
2.2.0で動くはずです．

**Comment by kuroky49** [comment]
はい，動くことを確認しました．使いやすくなったと思います；ありがとうございました．

具体的には以下を確認しました：

* （想定している拡張子に対して）出力先ファイル名・プルダウンボックス・参照ボックスがそれぞれ連携していること
* 出力先ファイル名に知らない拡張子（たとえば .jpeg）が与えられると，プルダウンボックス・参照ボックスの「ファイルの種類」は直前の動作を維持すること
