### ISSUE TITLE
Windows版TeX2imgのアイコン

### ISSUE THREAD

**Issue by doraTeX** [abenori/TeX2img#7]
このたび，デザイナーさんにMac版TeX2imgのアイコンを作って頂き，多数の案の中から1つに絞って，Mac版 Ver. 2.2.1 でアイコンを変更しました。
最終的に絞り込む直前の案の一覧を示します。いずれもmacOS風のデザインではありますが，[以前おっしゃっていた](https://github.com/doraTeX/TeX2img/issues/51#issuecomment-149038863)ように，もしご希望でしたら，お好みのアイコンを指定してくだされば，その高解像度データをお送りいたします。もちろん，現状のアイコンのままの方がよいということであればそれでも結構です。

**Comment by abenori** [comment]
おお，すごいですね．確かにMacっぽいですが，Windows上であってもそこまで違和感ないかなぁと思うので，折角なので使えるならば使わせてもらった方がよいかなぁ，と思います．同じのでいいかな？Windowsならこれだろ，とかあります？

**Comment by doraTeX** [comment]
従来，Mac版は青，Win版は緑で「色違い」でしたから，それを継承するならば，第1行第3,4列の緑系でしょうか？（この2つはほぼ同じですが，よく見ると「輪郭部のリングに柄が入っているか否か」が違います。）

**Comment by abenori** [comment]
それがよさそうですね．なんとなく四列目がよいでしょうか．

**Comment by doraTeX** [comment]
では4列目のデータをお渡しいたします。どうぞご活用ください。サイズ別PNGデータが入っています。32x32以下は，大サイズデータの相似縮小ではなく，低解像度用簡略デザインになっています。
[TeX2img_win_icon.zip](https://github.com/abenori/TeX2img/files/1973323/TeX2img_win_icon.zip)

**Comment by abenori** [comment]
ありがとうございます．とりあえずダウンロードしました．

**Comment by doraTeX** [comment]
はい、そのご理解で結構です。よろしくお願いします！
